title: Felipe J Col칩n-Gonz치lez # your name (or website title) here
logo: "/images/felipe_colon.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
I graduated from the National Autonomous University of Mexico in 1998 with a BSc in 
Veterinary Medicine. I worked as a Veterinary Surgeon in Mexico until 2007 with a particular
interest in zoonotic diseases. In 2008, I graduated from the University of East Anglia with 
an MSc in Environmental Sciences. In 2013, I obtained a PhD in Climate Change and Human Health
from the University of East Anglia. My PhD thesis focused on the role of climate and climate 
change on the risk of dengue transmission in Mexico.
  <br><br>
  Second description 
  <br><br>
  <a href="https://www.linkedin.com/in/felipe-j-col칩n-gonz치lez-a195368/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
